---
services:  
  db-bot:
    build: ./db
    restart: always
    container_name: chatty-db-service
    depends_on:
      - mongodb-bot
    networks:
      - internal
    env_file:
      - ./db/.env
    ports:
      - 8083:8080
  
  matcher-bot:
    build: ./matcher
    restart: always
    container_name: chatty-matcher-service
    depends_on:
      - db-bot
    networks:
      - internal
    env_file:
      - ./matcher/.env
    ports:
      - 8081:8081

  unsolved-bot:
    build: ./unsolveddb
    restart: always
    container_name: chatty-unsolved-service
    depends_on:
      - matcher-bot
    networks:
      - internal
    env_file:
      - ./unsolveddb/.env
    ports:
      - 8280:8080
    
  mail-bot:
    build: ./mailClient
    restart: always
    container_name: chatty-mail-service
    depends_on:
      - unsolved-bot
    networks:
      - internal
    env_file:
      - ./mailClient/.env
  
  api-bot:
    build: ./api
    restart: always
    container_name: chatty-api-service
    depends_on:
      - tokenizer-bot
      - logger-bot
    networks:
      - internal
    ports:
      - 8180:8080
    env_file:
      - ./api/.env

  logger-bot:
    build: ./logging
    restart: always
    container_name: chatty-logging-service
    depends_on:
      - redis-db
    networks:
      - internal
    env_file:
      - ./logging/.env
  
  tokenizer-bot:
    build: ./tokenizer
    restart: always
    container_name: chatty-tokenizer-service
    depends_on:
      - matcher-bot
    networks:
      - internal
    env_file:
      - ./tokenizer/.env
    ports:
      - 8080:8080

  unsolved-db:
    image: mongodb/mongodb-community-server:latest
    restart: always
    container_name: chatty-unsolved-db
    networks:
      - internal
    volumes:
      - mongodb-unsolved-data:/data/db
      - ./unsolveddb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - ./mongounsolveddb.env

  mongodb-bot:
    image: mongodb/mongodb-community-server:latest
    restart: always
    container_name: chatty-matcher-db
    networks:
      - internal
    volumes:
      - mongodb-data:/data/db
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - ./mongodb.env

  mongodb-admin:
    image: mongo-express:latest
    restart: always
    container_name: chatty-mongo-admin
    depends_on:
      - mongodb-bot
    networks:
      - internal
    env_file:
      - ./atlas.env
    ports:
      - 8082:8081

  redis-db:
    image: redis:6.2-alpine
    restart: always
    container_name: chatty-logging-db
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - internal
    volumes:
      - redis-data:/data

networks:
  internal:

volumes:
  mongodb-data:
  mongodb-unsolved-data:
  redis-data:
